// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	big "math/big"

	context "context"

	ethereum "github.com/ethereum/go-ethereum"

	mock "github.com/stretchr/testify/mock"

	time "time"

	types "github.com/ethereum/go-ethereum/core/types"
)

// EthClient is an autogenerated mock type for the EthClient type
type EthClient struct {
	mock.Mock
}

type EthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EthClient) EXPECT() *EthClient_Expecter {
	return &EthClient_Expecter{mock: &_m.Mock}
}

// HeaderByNumber provides a mock function with given fields: ctx, number
func (_m *EthClient) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Header, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Header); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type EthClient_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number *big.Int
func (_e *EthClient_Expecter) HeaderByNumber(ctx interface{}, number interface{}) *EthClient_HeaderByNumber_Call {
	return &EthClient_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", ctx, number)}
}

func (_c *EthClient_HeaderByNumber_Call) Run(run func(ctx context.Context, number *big.Int)) *EthClient_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*big.Int))
	})
	return _c
}

func (_c *EthClient_HeaderByNumber_Call) Return(_a0 *types.Header, _a1 error) *EthClient_HeaderByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_HeaderByNumber_Call) RunAndReturn(run func(context.Context, *big.Int) (*types.Header, error)) *EthClient_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// Latency provides a mock function with given fields: ctx, method
func (_m *EthClient) Latency(ctx context.Context, method string) (time.Duration, error) {
	ret := _m.Called(ctx, method)

	if len(ret) == 0 {
		panic("no return value specified for Latency")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return rf(ctx, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = rf(ctx, method)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_Latency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Latency'
type EthClient_Latency_Call struct {
	*mock.Call
}

// Latency is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
func (_e *EthClient_Expecter) Latency(ctx interface{}, method interface{}) *EthClient_Latency_Call {
	return &EthClient_Latency_Call{Call: _e.mock.On("Latency", ctx, method)}
}

func (_c *EthClient_Latency_Call) Run(run func(ctx context.Context, method string)) *EthClient_Latency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *EthClient_Latency_Call) Return(_a0 time.Duration, _a1 error) *EthClient_Latency_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_Latency_Call) RunAndReturn(run func(context.Context, string) (time.Duration, error)) *EthClient_Latency_Call {
	_c.Call.Return(run)
	return _c
}

// PeerCount provides a mock function with given fields: ctx
func (_m *EthClient) PeerCount(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PeerCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_PeerCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerCount'
type EthClient_PeerCount_Call struct {
	*mock.Call
}

// PeerCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthClient_Expecter) PeerCount(ctx interface{}) *EthClient_PeerCount_Call {
	return &EthClient_PeerCount_Call{Call: _e.mock.On("PeerCount", ctx)}
}

func (_c *EthClient_PeerCount_Call) Run(run func(ctx context.Context)) *EthClient_PeerCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthClient_PeerCount_Call) Return(_a0 uint64, _a1 error) *EthClient_PeerCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_PeerCount_Call) RunAndReturn(run func(context.Context) (uint64, error)) *EthClient_PeerCount_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeNewHead provides a mock function with given fields: ctx, ch
func (_m *EthClient) SubscribeNewHead(ctx context.Context, ch chan<- *types.Header) (ethereum.Subscription, error) {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeNewHead")
	}

	var r0 ethereum.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chan<- *types.Header) (ethereum.Subscription, error)); ok {
		return rf(ctx, ch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chan<- *types.Header) ethereum.Subscription); ok {
		r0 = rf(ctx, ch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ethereum.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chan<- *types.Header) error); ok {
		r1 = rf(ctx, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_SubscribeNewHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeNewHead'
type EthClient_SubscribeNewHead_Call struct {
	*mock.Call
}

// SubscribeNewHead is a helper method to define mock.On call
//   - ctx context.Context
//   - ch chan<- *types.Header
func (_e *EthClient_Expecter) SubscribeNewHead(ctx interface{}, ch interface{}) *EthClient_SubscribeNewHead_Call {
	return &EthClient_SubscribeNewHead_Call{Call: _e.mock.On("SubscribeNewHead", ctx, ch)}
}

func (_c *EthClient_SubscribeNewHead_Call) Run(run func(ctx context.Context, ch chan<- *types.Header)) *EthClient_SubscribeNewHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chan<- *types.Header))
	})
	return _c
}

func (_c *EthClient_SubscribeNewHead_Call) Return(_a0 ethereum.Subscription, _a1 error) *EthClient_SubscribeNewHead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_SubscribeNewHead_Call) RunAndReturn(run func(context.Context, chan<- *types.Header) (ethereum.Subscription, error)) *EthClient_SubscribeNewHead_Call {
	_c.Call.Return(run)
	return _c
}

// SyncProgress provides a mock function with given fields: ctx
func (_m *EthClient) SyncProgress(ctx context.Context) (*ethereum.SyncProgress, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncProgress")
	}

	var r0 *ethereum.SyncProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ethereum.SyncProgress, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ethereum.SyncProgress); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethereum.SyncProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_SyncProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncProgress'
type EthClient_SyncProgress_Call struct {
	*mock.Call
}

// SyncProgress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthClient_Expecter) SyncProgress(ctx interface{}) *EthClient_SyncProgress_Call {
	return &EthClient_SyncProgress_Call{Call: _e.mock.On("SyncProgress", ctx)}
}

func (_c *EthClient_SyncProgress_Call) Run(run func(ctx context.Context)) *EthClient_SyncProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthClient_SyncProgress_Call) Return(_a0 *ethereum.SyncProgress, _a1 error) *EthClient_SyncProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_SyncProgress_Call) RunAndReturn(run func(context.Context) (*ethereum.SyncProgress, error)) *EthClient_SyncProgress_Call {
	_c.Call.Return(run)
	return _c
}

// NewEthClient creates a new instance of EthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthClient {
	mock := &EthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
