// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HealthCheckManager is an autogenerated mock type for the HealthCheckManager type
type HealthCheckManager struct {
	mock.Mock
}

// GetHealthyUpstreams provides a mock function with given fields:
func (_m *HealthCheckManager) GetHealthyUpstreams() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// StartHealthChecks provides a mock function with given fields:
func (_m *HealthCheckManager) StartHealthChecks() {
	_m.Called()
}

type mockConstructorTestingTNewHealthCheckManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewHealthCheckManager creates a new instance of HealthCheckManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHealthCheckManager(t mockConstructorTestingTNewHealthCheckManager) *HealthCheckManager {
	mock := &HealthCheckManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
