// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	types "github.com/satsuma-data/node-gateway/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// LatencyChecker is an autogenerated mock type for the LatencyChecker type
type LatencyChecker struct {
	mock.Mock
}

type LatencyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *LatencyChecker) EXPECT() *LatencyChecker_Expecter {
	return &LatencyChecker_Expecter{mock: &_m.Mock}
}

// IsPassing provides a mock function with given fields:
func (_m *LatencyChecker) IsPassing() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPassing")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LatencyChecker_IsPassing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPassing'
type LatencyChecker_IsPassing_Call struct {
	*mock.Call
}

// IsPassing is a helper method to define mock.On call
func (_e *LatencyChecker_Expecter) IsPassing() *LatencyChecker_IsPassing_Call {
	return &LatencyChecker_IsPassing_Call{Call: _e.mock.On("IsPassing")}
}

func (_c *LatencyChecker_IsPassing_Call) Run(run func()) *LatencyChecker_IsPassing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LatencyChecker_IsPassing_Call) Return(_a0 bool) *LatencyChecker_IsPassing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LatencyChecker_IsPassing_Call) RunAndReturn(run func() bool) *LatencyChecker_IsPassing_Call {
	_c.Call.Return(run)
	return _c
}

// RecordRequest provides a mock function with given fields: data
func (_m *LatencyChecker) RecordRequest(data *types.RequestData) {
	_m.Called(data)
}

// LatencyChecker_RecordRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRequest'
type LatencyChecker_RecordRequest_Call struct {
	*mock.Call
}

// RecordRequest is a helper method to define mock.On call
//   - data *types.RequestData
func (_e *LatencyChecker_Expecter) RecordRequest(data interface{}) *LatencyChecker_RecordRequest_Call {
	return &LatencyChecker_RecordRequest_Call{Call: _e.mock.On("RecordRequest", data)}
}

func (_c *LatencyChecker_RecordRequest_Call) Run(run func(data *types.RequestData)) *LatencyChecker_RecordRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.RequestData))
	})
	return _c
}

func (_c *LatencyChecker_RecordRequest_Call) Return() *LatencyChecker_RecordRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *LatencyChecker_RecordRequest_Call) RunAndReturn(run func(*types.RequestData)) *LatencyChecker_RecordRequest_Call {
	_c.Call.Return(run)
	return _c
}

// RunPassiveCheck provides a mock function with given fields:
func (_m *LatencyChecker) RunPassiveCheck() {
	_m.Called()
}

// LatencyChecker_RunPassiveCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunPassiveCheck'
type LatencyChecker_RunPassiveCheck_Call struct {
	*mock.Call
}

// RunPassiveCheck is a helper method to define mock.On call
func (_e *LatencyChecker_Expecter) RunPassiveCheck() *LatencyChecker_RunPassiveCheck_Call {
	return &LatencyChecker_RunPassiveCheck_Call{Call: _e.mock.On("RunPassiveCheck")}
}

func (_c *LatencyChecker_RunPassiveCheck_Call) Run(run func()) *LatencyChecker_RunPassiveCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LatencyChecker_RunPassiveCheck_Call) Return() *LatencyChecker_RunPassiveCheck_Call {
	_c.Call.Return()
	return _c
}

func (_c *LatencyChecker_RunPassiveCheck_Call) RunAndReturn(run func()) *LatencyChecker_RunPassiveCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewLatencyChecker creates a new instance of LatencyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLatencyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *LatencyChecker {
	mock := &LatencyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
