// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RoutingStrategy is an autogenerated mock type for the RoutingStrategy type
type RoutingStrategy struct {
	mock.Mock
}

// RouteNextRequest provides a mock function with given fields: upstreamsByPriority
func (_m *RoutingStrategy) RouteNextRequest(upstreamsByPriority map[int][]string) string {
	ret := _m.Called(upstreamsByPriority)

	var r0 string
	if rf, ok := ret.Get(0).(func(map[int][]string) string); ok {
		r0 = rf(upstreamsByPriority)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewRoutingStrategy interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoutingStrategy creates a new instance of RoutingStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoutingStrategy(t mockConstructorTestingTNewRoutingStrategy) *RoutingStrategy {
	mock := &RoutingStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
