// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SimpleChecker is an autogenerated mock type for the SimpleChecker type
type SimpleChecker struct {
	mock.Mock
}

// IsPassing provides a mock function with given fields:
func (_m *SimpleChecker) IsPassing() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RunCheck provides a mock function with given fields:
func (_m *SimpleChecker) RunCheck() {
	_m.Called()
}

type mockConstructorTestingTNewSimpleChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewSimpleChecker creates a new instance of SimpleChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSimpleChecker(t mockConstructorTestingTNewSimpleChecker) *SimpleChecker {
	mock := &SimpleChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
